#!/usr/bin/env sh

git clone git@github.com:xrowgmbh/ezstudio.git
cd ezstudio
git remote add upstream git@github.com:ezsystems/ezstudio.git
git fetch upstream
git rebase upstream/master
git pull
git push origin master
cd ..
rm -Rf ezstudio
